/* Generated by Cython 3.0.12 */

#ifndef __PYX_HAVE__chemeng__NASAdata
#define __PYX_HAVE__chemeng__NASAdata

#include "Python.h"

#ifndef __PYX_HAVE_API__chemeng__NASAdata

#ifdef CYTHON_EXTERN_C
    #undef __PYX_EXTERN_C
    #define __PYX_EXTERN_C CYTHON_EXTERN_C
#elif defined(__PYX_EXTERN_C)
    #ifdef _MSC_VER
    #pragma message ("Please do not define the '__PYX_EXTERN_C' macro externally. Use 'CYTHON_EXTERN_C' instead.")
    #else
    #warning Please do not define the '__PYX_EXTERN_C' macro externally. Use 'CYTHON_EXTERN_C' instead.
    #endif
#else
    #define __PYX_EXTERN_C extern "C++"
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C double R;

#endif /* !__PYX_HAVE_API__chemeng__NASAdata */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initNASAdata(void);
#else
/* WARNING: Use PyImport_AppendInittab("NASAdata", PyInit_NASAdata) instead of calling PyInit_NASAdata directly from Python 3.5 */
PyMODINIT_FUNC PyInit_NASAdata(void);

#if PY_VERSION_HEX >= 0x03050000 && (defined(__GNUC__) || defined(__clang__) || defined(_MSC_VER) || (defined(__cplusplus) && __cplusplus >= 201402L))
#if defined(__cplusplus) && __cplusplus >= 201402L
[[deprecated("Use PyImport_AppendInittab(\"NASAdata\", PyInit_NASAdata) instead of calling PyInit_NASAdata directly.")]] inline
#elif defined(__GNUC__) || defined(__clang__)
__attribute__ ((__deprecated__("Use PyImport_AppendInittab(\"NASAdata\", PyInit_NASAdata) instead of calling PyInit_NASAdata directly."), __unused__)) __inline__
#elif defined(_MSC_VER)
__declspec(deprecated("Use PyImport_AppendInittab(\"NASAdata\", PyInit_NASAdata) instead of calling PyInit_NASAdata directly.")) __inline
#endif
static PyObject* __PYX_WARN_IF_PyInit_NASAdata_INIT_CALLED(PyObject* res) {
  return res;
}
#define PyInit_NASAdata() __PYX_WARN_IF_PyInit_NASAdata_INIT_CALLED(PyInit_NASAdata())
#endif
#endif

#endif /* !__PYX_HAVE__chemeng__NASAdata */
